apiVersion: v1
kind: Service
metadata:
  name: monitoring-app
spec:
  type: LoadBalancer
  selector:
    app: monitoring-app
  ports:
    - port: 5000
      #targetPort is the port on which our application is running i.e. the container port
      targetPort: 5000
      #the port on which our application will mapped with the kind cluster
      nodePort: 30007
